server:
  port: 8080

spring:
  application:
    name: manager-app

  datasource:
    url: jdbc:postgresql://localhost:5440/manager
    username: manager
    password: manager
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
  flyway:
    locations: classpath:db/migration
    schemas:
      -public
      -user_management
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://127.0.0.1:8050/realms/selmag
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: manager-app
            client-secret: onsJgiT6Jetf1mF86MmM6Nht7t0a3v8W
            scope:
              - openid
              - view_catalogue
              - edit_catalogue
              - microprofile-jwt

selmag:
  services:
    catalogue:
      uri: http://localhost:8088
      registration-id: keycloak

logging:
  level:
    org.springframework.security: trace
