
server:
  port: 8088

spring:
  application:
    name: catalogue-service

  datasource:
    url: jdbc:postgresql://localhost:5430/selmag_catalogue
    username: catalogue
    password: catalogue
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
  flyway:
    locations: classpath:db/migration
    schemas:
      -public
      -catalogue

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:8050/realms/selmag

logging:
  level:
    sql: info
    org.springframework.security: trace
