server:
  port: 8889
  address: http://localhost:8889

spring:
  application:
    name: feedback-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/feedback-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:8050/realms/selmag

springdoc:
  swagger-ui:
    oauth:
      client-id: feedback-service-swagger-ui
      use-pkce-with-authorization-code-grant: true

#project variables

keycloak:
  uri: http://127.0.0.1:8050