server:
  port: 8888
spring:
  application:
    name: customer-app



#project variables
selmag:
  services:
    feedback:
      uri: http://localhost:8889
    catalogue:
      uri: http://localhost:8088